version: '3.1'
services:
  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toto

  app:
    build: .
    links:
      - "db"
    ports:
      - "3000:3000"